# Generated by Django 5.0.3 on 2024-03-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.PositiveSmallIntegerField(default=1)),
                ('weight', models.PositiveSmallIntegerField(default=100)),
                ('bacon', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('unique id', models.IntegerField()),
            ],
        ),
    ]
