# Generated by Django 5.0.4 on 2024-04-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_burgermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgermodel',
            name='meat',
            field=models.CharField(choices=[('CH', 'Chicken'), ('VG', 'Vegetarian'), ('ST', 'Steak'), ('FI', 'Fish')], default='CH', max_length=2, verbose_name='Meat'),
        ),
    ]
