# Generated by Django 5.0.4 on 2024-04-24 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_burgermodel_meat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgermodel',
            name='unique id',
            field=models.UUIDField(default=uuid.UUID('0b2a34a8-2001-43d2-9c58-922f8b1302ad')),
        ),
    ]
