# Generated by Django 5.0.4 on 2024-04-24 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_alter_burgermodel_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgermodel',
            name='Eaten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='burgermodel',
            name='unique id',
            field=models.UUIDField(default=uuid.UUID('e012aaf6-9cfe-4f9c-b064-28c06b8cb567')),
        ),
    ]
