# Generated by Django 5.0.4 on 2024-04-24 14:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_burgermodel_eaten_alter_burgermodel_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgermodel',
            name='unique id',
            field=models.UUIDField(default=uuid.UUID('c8f3fa48-7717-42b1-8d66-4e025a6c183f')),
        ),
    ]
