# Generated by Django 5.0.4 on 2024-04-24 14:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_alter_burgermodel_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burgermodel',
            name='Eaten',
        ),
        migrations.AlterField(
            model_name='burgermodel',
            name='unique id',
            field=models.UUIDField(default=uuid.UUID('274f5f46-2e36-45fa-91a7-4dffe3ad761e')),
        ),
    ]
